# This is a basic workflow to help you get started with Actions
name: Runner_test

defaults:
  run:
    shell: bash 

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on: [push, fork]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "bld_gnu_ompi"
  bld_nvhpc_ompi:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, x64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Run and Compile NHHPC for CPU
    - name: Compile NHVHPC CPU
      run: |
        ls -ltr ~/.bashrc
        source ~/.bashrc
        source ~/.profile_github
        echo $LMOD_CMD
        module avail
        module load CMake 
        module load nvhpc
        export FC=mpif90
        cmake -S . -B build -DBUILD_TESTING=ON
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build 
        cmake -S . -B build -DNX=128 -DNY=128 -DNX=128 -DMPIEXEC_MAX_NUMPROCS=4
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build 


