# This is a basic workflow to help you get started with Actions
name: Runner_test

defaults:
  run:
    shell: bash 

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on: [push, fork]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "bld_gnu_ompi"
  Full_CI_workflow:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, x64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
      with: 
        clean: true

    # Run and Compile NHHPC for CPU
    - name: Compile NHVHPC CPU
      run: |
        ls -ltr ~/.bashrc
        source ~/.bashrc
        source ~/.profile_github
        module load CMake 
        module load nvhpc
        export FC=mpif90
        cmake -S . -B build -DBUILD_TESTING=ON
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build 
        cmake -S . -B build -DNX=128 -DNY=128 -DNX=128 -DMPIEXEC_MAX_NUMPROCS=4
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build
        rm -rf build  
    
    # Run and Compile NHHPC for CPU with ADIOS2
    # Need to fix issue with latest NVHPC and ADIOS
    # Need to revert to 23.1
    - name: Compile NHVHPC CPU & ADIOS2
      run: |
        ls -ltr ~/.bashrc
        source ~/.bashrc
        source ~/.profile_github
        module load CMake 
        module load nvhpc/23.1
        export FC=mpif90
        export CC=mpicc
        export CXX=mpicxx
        cmake -S . -B build -DBUILD_TESTING=ON -DIO_BACKEND=adios2 -Dadios2_DIR=~/GIT_Work/ADIOS2/build_install_nvhpc_cpu/opt/lib/cmake/adios2
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build 
        cmake -S . -B build -DNX=128 -DNY=128 -DNX=128 -DMPIEXEC_MAX_NUMPROCS=4
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build
        rm -rf build  
    
    # Run and Compile NHHPC for GPU & cuMPI
    - name: Compile NHVHPC GPU cuMPI
      run: |
        ls -ltr ~/.bashrc
        source ~/.bashrc
        source ~/.profile_github
        module load CMake 
        module load nvhpc
        export FC=mpif90
        cmake -S . -B build -DBUILD_TESTING=ON -DBUILD_TARGET=gpu -DENABLE_NCCL=no
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build 
        cmake -S . -B build -DNX=128 -DNY=128 -DNX=128
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build
        rm -rf build  
    
    # Run and Compile NHHPC for GPU & NCCL
    - name: Compile NHVHPC GPU NCCL
      run: |
        ls -ltr ~/.bashrc
        source ~/.bashrc
        source ~/.profile_github
        module load CMake 
        module load nvhpc
        export FC=mpif90
        cmake -S . -B build -DBUILD_TESTING=ON -DBUILD_TARGET=gpu -DENABLE_NCCL=yes
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build 
        cmake -S . -B build -DNX=128 -DNY=128 -DNX=128
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build
        rm -rf build  
    
    # Run and Compile NHHPC for GPU & NCCL & Memory Managment
    - name: Compile NHVHPC GPU NCCL MemManag
      run: |
        ls -ltr ~/.bashrc
        source ~/.bashrc
        source ~/.profile_github
        module load CMake 
        module load nvhpc
        export FC=mpif90
        cmake -S . -B build -DBUILD_TESTING=ON -DBUILD_TARGET=gpu -DENABLE_NCCL=yes -DENABLE_MANAGED=yes
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build 
        cmake -S . -B build -DNX=128 -DNY=128 -DNX=128
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build
        rm -rf build  

    # Run and Compile with GCC openMPI and FFTW
    - name: Compile GNU openMPI FFTW CPU
      run: |
        ls -ltr ~/.bashrc
        source ~/.bashrc
        source ~/.profile_github
        module load CMake 
        module load foss
        export FC=mpif90
        cmake -S . -B build -DBUILD_TESTING=ON -DFFT_Choice=fftw
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build 
        cmake -S . -B build -DNX=128 -DNY=128 -DNX=128 -DMPIEXEC_MAX_NUMPROCS=4
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build
        rm -rf build  

    # Run and Compile with GCC openMPI and FFTW
    - name: Compile GNU openMPI FFTW_F03 CPU
      run: |
        ls -ltr ~/.bashrc
        source ~/.bashrc
        source ~/.profile_github
        module load CMake 
        module load foss
        export FC=mpif90
        cmake -S . -B build -DBUILD_TESTING=ON -DFFT_Choice=fftw_f03
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build 
        cmake -S . -B build -DNX=128 -DNY=128 -DNX=128 -DMPIEXEC_MAX_NUMPROCS=4
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build
        rm -rf build  
    
    # Run and Compile with GCC openMPI and FFTW
    - name: Compile GNU_Dev openMPI FFTW_F03 ADIOS2 CPU
      run: |
        ls -ltr ~/.bashrc
        source ~/.bashrc
        source ~/.profile_github
        module load CMake 
        module load foss
        export FC=mpif90
        export CC=mpicc
        export CXX=mpicxx
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Dev -DBUILD_TESTING=ON -DIO_BACKEND=adios2 -Dadios2_DIR=~/GIT_Work/ADIOS2/build_install_gcc12_cpu/opt/lib/cmake/adios2 -DFFT_Choice=fftw_f03
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build 
        cmake -S . -B build -DNX=128 -DNY=128 -DNX=128 -DMPIEXEC_MAX_NUMPROCS=4
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build
        rm -rf build  
