# This is a basic workflow to help you get started with Actions

name: Runner_test

defaults:
  run:
    shell: bash 

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on: [push, fork]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "bld_gnu_ompi"
  bld_nvhpc_ompi:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, x64]


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3


    # Runs a single command using the runners shell
    - name: Install requirements
      run: |
        #env
        ls -ltr ~/.bashrc
        echo "Start source" 
        source ~/.bashrc
        echo "Ok source profile" 
        echo "Ok source profile" 
        source ~/.profile_github
        echo "Ok source local .profile" 
        echo $LMOD_CMD
        #module avail 
        #cd ~
        #ls *
        #. ./.bashrc
        #cd -
        #module avail 
        #module load nvhpc
        #module list

    # Runs a set of commands using the runners shell
    - name: Compile
      run: |
        which cmake
        export FC=mpif90
        cmake -S . -B build -DBUILD_TESTING=ON
        cmake --build build --target decomp2d
        cmake --install build 

        #sudo apt-get update
        #sudo apt-get install -y gfortran 
        #sudo apt-get install -y openmpi-bin 
        #sudo apt-get install -y libopenmpi-dev 
        #sudo apt-get install -y cmake
