# This is a basic workflow to help you get started with Actions
name: FullCI4PR_gnu_double

defaults:
  run:
    shell: bash 

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on: [pull_request, fork]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "bld_gnu_ompi"
  Full_CI_GNU_double:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, x64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
      with: 
        clean: true

    # Configure-Build-Run-Run on 4 cores 
    - name: Compile GNU openMPI FFTW CPU
      run: |
        ls -ltr ~/.bashrc
        source /etc/profile.d/lmod.sh
        source ~/.bash_aliases
        module load foss
        export FC=mpif90
        cmake -S . -B build -DBUILD_TESTING=ON -DFFT_Choice=fftw
        cmake -S . -B build -DNX=128 -DNY=128 -DNX=128 -DMPIEXEC_MAX_NUMPROCS=4
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build
        rm -rf build  

    # Configure-Build-Run-Run on 4 cores 
    - name: Compile GNU openMPI FFTW_F03 CPU
      run: |
        ls -ltr ~/.bashrc
        source /etc/profile.d/lmod.sh
        source ~/.bash_aliases
        module load foss
        export FC=mpif90
        cmake -S . -B build -DBUILD_TESTING=ON -DFFT_Choice=fftw_f03
        cmake -S . -B build -DNX=128 -DNY=128 -DNX=128 -DMPIEXEC_MAX_NUMPROCS=4
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build
        rm -rf build

    # Configure-Build-Run-Run on 4 cores 
    - name: Compile GNU openMPI FFTW_F03 Caliper CPU
      run: |
        ls -ltr ~/.bashrc
        source /etc/profile.d/lmod.sh
        source ~/.bash_aliases
        module load foss
        export FC=mpif90
        export CC=mpicc
        export CXX=mpicxx
        export caliper_DIR=~/GIT/caliper_github/build_foss2023b/opt/share/cmake/caliper/
        cmake -S . -B build -DBUILD_TESTING=ON -DFFT_Choice=fftw_f03 -DENABLE_PROFILER=caliper
        cmake -S . -B build -DMPIEXEC_MAX_NUMPROCS=4
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build
        rm -rf build  
    
    # Configure-Build-Run-Run on 4 cores 
    - name: Compile GNU_Dev openMPI FFTW_F03 ADIOS2 CPU
      run: |
        ls -ltr ~/.bashrc
        source /etc/profile.d/lmod.sh
        source ~/.bash_aliases
        module load foss
        export FC=mpif90
        export CC=mpicc
        export CXX=mpicxx
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Dev -DBUILD_TESTING=ON -DIO_BACKEND=adios2 -Dadios2_DIR=~/GIT/ADIOS2/build/build_foss2023b/opt/lib/cmake/adios2 -DFFT_Choice=fftw_f03
        cmake -S . -B build -DNX=128 -DNY=128 -DNX=128 -DMPIEXEC_MAX_NUMPROCS=4
        cmake --build build -j 4
        cmake --install build #ctest --test-dir build
        rm -rf build

    # Configure-Build-Run-Run on 4 cores 
    - name: Compile GNU_Dev openMPI FFTW_F03 SINGLE_PRECISION_OUTPUT CPU
      run: |
        ls -ltr ~/.bashrc
        source /etc/profile.d/lmod.sh
        source ~/.bash_aliases
        module load foss
        export FC=mpif90
        export CC=mpicc
        export CXX=mpicxx
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Dev -DBUILD_TESTING=ON -DFFT_Choice=fftw_f03 -DSINGLE_PRECISION_OUTPUT=on
        cmake -S . -B build -DNX=128 -DNY=128 -DNX=128 -DMPIEXEC_MAX_NUMPROCS=4
        cmake --build build -j 4
        cmake --install build 
        ctest --test-dir build
        rm -rf build
